import type { Metadata } from 'next'
// import { Poppins } from 'next/font/google'
import './globals.css'

// const poppins = Poppins({
//   weight: ['400', '500', '600', '700'],
//   subsets: ['latin'],
// })

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <main className="h-screen overflow-y-auto">{children}</main>
      </body>
    </html>
  )
}
